name: com.mohamed.dev_server
description: A Flutter application with auto-update support
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # GetX لإدارة الحالة والمسارات والتبعيات
  get: ^4.7.2

  # لقاعدة البيانات SQLite
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2+1
  path: ^1.9.0
  path_provider: ^2.1.2

  # للتحقق من الاتصال
  connectivity_plus: ^5.0.2

  # للتاريخ والوقت
  intl: ^0.19.0

  # للتحديثات التلقائية
  package_info_plus: ^8.3.0
  url_launcher: ^6.2.5
  dio: ^5.4.1
  version: ^3.0.2
  open_filex: ^4.3.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^5.0.0

  # لسكربتات الأدوات
  yaml: ^3.1.2
  yaml_edit: ^2.1.1
  github: ^9.24.0
  archive: ^3.4.10

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/animations/
    - assets/data/

  # Fonts
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300

