name: core_services_package
description: Core services for Dev Server app
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  dio: ^5.4.1
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  path: ^1.9.0
  path_provider: ^2.1.2
  intl: ^0.19.0
  version: ^3.0.2
  open_filex: ^4.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
