name: auto_update_package
description: Auto-update functionality for Dev Server app
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.1
  package_info_plus: ^8.3.0
  url_launcher: ^6.2.5
  version: ^3.0.2
  open_filex: ^4.3.4
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
