name: tools_package
description: Development tools for Dev Server app
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  github: ^9.25.0
  yaml: ^3.1.2
  yaml_edit: ^2.1.1
  archive: ^3.4.10
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
